import type { Property } from "./types"

export const properties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Apartment",
    description: "Luxurious apartment in the heart of the city with stunning views and modern amenities.",
    price: 850000,
    location: "Downtown District",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    type: "apartment",
    images: [
      "https://picsum.photos/400/300?random=10",
      "https://picsum.photos/400/300?random=11",
      "https://picsum.photos/400/300?random=12",
    ],
    featured: true,
    virtualTour: {
      id: "tour-1",
      initialScene: "living-room",
      scenes: [
        {
          id: "living-room",
          name: "Living Room",
          image360: "https://picsum.photos/2048/1024?random=20",
          description: "Spacious living room with floor-to-ceiling windows",
          hotspots: [
            {
              id: "to-kitchen",
              type: "navigation",
              position: { x: 0.5, y: 0, z: -0.8 },
              targetScene: "kitchen",
              title: "Go to Kitchen",
              icon: "arrow-right",
            },
            {
              id: "to-bedroom",
              type: "navigation",
              position: { x: -0.8, y: 0, z: 0.2 },
              targetScene: "bedroom",
              title: "Go to Bedroom",
              icon: "arrow-right",
            },
            {
              id: "window-info",
              type: "info",
              position: { x: 0, y: 0.3, z: -0.9 },
              title: "City View",
              description: "Panoramic view of the downtown skyline",
            },
          ],
        },
        {
          id: "kitchen",
          name: "Kitchen",
          image360: "https://picsum.photos/2048/1024?random=21",
          description: "Modern kitchen with premium appliances",
          hotspots: [
            {
              id: "to-living",
              type: "navigation",
              position: { x: -0.5, y: 0, z: 0.8 },
              targetScene: "living-room",
              title: "Back to Living Room",
              icon: "arrow-left",
            },
            {
              id: "appliances-info",
              type: "info",
              position: { x: 0.7, y: 0, z: -0.3 },
              title: "Premium Appliances",
              description: "Stainless steel appliances including dishwasher, microwave, and refrigerator",
            },
          ],
        },
        {
          id: "bedroom",
          name: "Master Bedroom",
          image360: "https://picsum.photos/2048/1024?random=22",
          description: "Comfortable master bedroom with ensuite bathroom",
          hotspots: [
            {
              id: "to-living",
              type: "navigation",
              position: { x: 0.8, y: 0, z: -0.2 },
              targetScene: "living-room",
              title: "Back to Living Room",
              icon: "arrow-left",
            },
            {
              id: "to-bathroom",
              type: "navigation",
              position: { x: -0.6, y: 0, z: -0.6 },
              targetScene: "bathroom",
              title: "Go to Bathroom",
              icon: "arrow-right",
            },
          ],
        },
        {
          id: "bathroom",
          name: "Bathroom",
          image360: "https://picsum.photos/2048/1024?random=23",
          description: "Luxurious bathroom with modern fixtures",
          hotspots: [
            {
              id: "to-bedroom",
              type: "navigation",
              position: { x: 0.6, y: 0, z: 0.6 },
              targetScene: "bedroom",
              title: "Back to Bedroom",
              icon: "arrow-left",
            },
          ],
        },
      ],
    },
  },
  {
    id: "2",
    title: "Spacious Family Villa",
    description: "Beautiful villa with garden, perfect for families seeking comfort and space.",
    price: 1200000,
    location: "Suburban Area",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2500,
    type: "villa",
    images: [
      "https://picsum.photos/400/300?random=13",
      "https://picsum.photos/400/300?random=14",
      "https://picsum.photos/400/300?random=15",
    ],
    featured: true,
    virtualTour: {
      id: "tour-2",
      initialScene: "entrance",
      scenes: [
        {
          id: "entrance",
          name: "Entrance Hall",
          image360: "https://picsum.photos/2048/1024?random=24",
          description: "Grand entrance with high ceilings",
          hotspots: [
            {
              id: "to-living",
              type: "navigation",
              position: { x: 0, y: 0, z: -0.9 },
              targetScene: "living-room",
              title: "Go to Living Room",
              icon: "arrow-right",
            },
            {
              id: "to-garden",
              type: "navigation",
              position: { x: 0.8, y: 0, z: 0 },
              targetScene: "garden",
              title: "Go to Garden",
              icon: "arrow-right",
            },
          ],
        },
        {
          id: "living-room",
          name: "Living Room",
          image360: "https://picsum.photos/2048/1024?random=25",
          description: "Spacious living area with fireplace",
          hotspots: [
            {
              id: "to-entrance",
              type: "navigation",
              position: { x: 0, y: 0, z: 0.9 },
              targetScene: "entrance",
              title: "Back to Entrance",
              icon: "arrow-left",
            },
          ],
        },
        {
          id: "garden",
          name: "Garden",
          image360: "https://picsum.photos/2048/1024?random=26",
          description: "Beautiful landscaped garden",
          hotspots: [
            {
              id: "to-entrance",
              type: "navigation",
              position: { x: -0.8, y: 0, z: 0 },
              targetScene: "entrance",
              title: "Back to Entrance",
              icon: "arrow-left",
            },
          ],
        },
      ],
    },
  },
  {
    id: "3",
    title: "Cozy Studio Condo",
    description: "Perfect starter home with modern finishes and great location near public transport.",
    price: 450000,
    location: "Metro District",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    type: "condo",
    images: [
      "https://picsum.photos/400/300?random=16",
      "https://picsum.photos/400/300?random=17",
      "https://picsum.photos/400/300?random=18",
    ],
    featured: false,
  },
  {
    id: "4",
    title: "Luxury Penthouse",
    description: "Exclusive penthouse with panoramic city views and premium amenities.",
    price: 2500000,
    location: "Premium District",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1800,
    type: "apartment",
    images: [
      "https://picsum.photos/400/300?random=19",
      "https://picsum.photos/400/300?random=30",
      "https://picsum.photos/400/300?random=31",
    ],
    featured: true,
    virtualTour: {
      id: "tour-4",
      initialScene: "main-living",
      scenes: [
        {
          id: "main-living",
          name: "Main Living Area",
          image360: "https://picsum.photos/2048/1024?random=27",
          description: "Luxurious living space with panoramic city views",
          hotspots: [
            {
              id: "to-terrace",
              type: "navigation",
              position: { x: 0, y: 0, z: -0.9 },
              targetScene: "terrace",
              title: "Go to Terrace",
              icon: "arrow-right",
            },
            {
              id: "city-view",
              type: "info",
              position: { x: -0.8, y: 0.2, z: -0.3 },
              title: "City Skyline",
              description: "180-degree panoramic view of the city skyline",
            },
          ],
        },
        {
          id: "terrace",
          name: "Private Terrace",
          image360: "https://picsum.photos/2048/1024?random=28",
          description: "Private terrace with outdoor seating",
          hotspots: [
            {
              id: "to-living",
              type: "navigation",
              position: { x: 0, y: 0, z: 0.9 },
              targetScene: "main-living",
              title: "Back to Living Room",
              icon: "arrow-left",
            },
          ],
        },
      ],
    },
  },
  {
    id: "5",
    title: "Elegant Townhouse",
    description: "Charming townhouse with modern amenities and classic architecture.",
    price: 750000,
    location: "Historic District",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    type: "house",
    images: [
      "https://picsum.photos/400/300?random=32",
      "https://picsum.photos/400/300?random=33",
      "https://picsum.photos/400/300?random=34",
    ],
    featured: true,
  },
  {
    id: "6",
    title: "Waterfront Condo",
    description: "Stunning waterfront property with marina access and luxury amenities.",
    price: 1800000,
    location: "Marina District",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1400,
    type: "condo",
    images: [
      "https://picsum.photos/400/300?random=35",
      "https://picsum.photos/400/300?random=36",
      "https://picsum.photos/400/300?random=37",
    ],
    featured: false,
  },
]

export function getPropertyById(id: string): Property | undefined {
  return properties.find((property) => property.id === id)
}
